CREATE DATABASE animals;

CREATE TABLE users(
    u_id SERIAL PRIMARY KEY NOT NULL,
    username VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password VARCHAR(50) NOT NULL,
    UNIQUE (email)
);

CREATE TABLE Category(
    id SERIAL PRIMARY KEY NOT NULL,
    Name VARCHAR (200) NOT NULL
);

CREATE TABLE Animal(
    animal_id SERIAL PRIMARY KEY NOT NULL,
    CategoryID SERIAL NOT NULL,
    A_Name VARCHAR(200) NOT NULL,
    Breed VARCHAR(100) NOT NULL,
    Age VARCHAR(2) NOT NULL,
    Sex VARCHAR(10) NOT NULL,
    Health VARCHAR(200) NOT NULL
);

ALTER TABLE Animal ADD COLUMN "Vaccined" BOOLEAN DEFAULT FALSE;
